version: '3.1'

services:
  app: 
    container_name: app-golang-api
    build: 
      dockerfile: Dockerfile
    command: go run main.go
    ports:
      - 8080:8080
    networks:
     - api
    depends_on:
      - db   
  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
     - 5432:5432   
    networks:
     - api 
networks:
  api: